# Render configuration for backend deployment
services:
  - type: web
    name: gif-converter-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm ci --omit=dev --verbose
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: NPM_CONFIG_UNSAFE_PERM
        value: "true"
      - key: CANVAS_PREBUILT
        value: "1"
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /api/convert/test